### ISSUE TITLE
checkpointing is broken after the libmrc update

### ISSUE THREAD

**Issue by abbotts** [psc-code/psc#1]
The new libmrc only allows "hdf5_serial" to read coordinates. psc_checkpoint.c hardcodes the method to "xdmf_serial", so it trips the assert. Simple test script is attached (path to bin will need to be changed, I run from the 'bits' directory. Test script is bash, but has a .txt extension because apparently github doesn't like .cmd).
[test_kh_hdf5_checkpoint.txt](https://github.com/psc-code/psc/files/920683/test_kh_hdf5_checkpoint.txt)

**Comment by abbotts** [comment]
Editing "psc_checkpoint.c" to use "hdf5_serial" seems to work fine (as expected), with the exception that I see some diffs in uids for mrc_ddc, mrc_domain, and mrc_crds objects. 

Normally I would expect the uid written and read from the checkpoint. @germasch Are we regenerating them now? If these uids changes are expected, this issue can be closed, since the patch is trivial to implement.

FWIW, the new adios method I'm working on passes this simple test as well, but with the same uid differences.

[run_hdf5.txt](https://github.com/psc-code/psc/files/920700/run_hdf5.txt)

**Comment by germasch** [comment]
I'm pretty sure that the uid's are newly created when reading back a checkpoint, so may well change. I think the rationale behind that was that normally the uid is the pointer to the object to make sure it's unique, and when restoring the uid from a file, it's in theory possible that a newly allocated object, which uses the pointer as uid would end up with the same uid as some other object with a restored uid.

Not that I like any of the uid mess...

**Comment by germasch** [comment]
Checkpointing actually now uses ADIOS2 (though it needs more work), and I got rid of the uids at least on that side ;)

While it's unfortunate that the adios1 work never got merged, I'd think by now it's kinda superseded by ADIOS2.
