### ISSUE TITLE
flatfoil code breaking anomalously at step 200

### ISSUE THREAD

**Issue by jackmatt16** [psc-code/psc#65]
Code breaks right after collisions and sorting - I am outputing at step 200. 

I've modified a couple parameters trivially, but non-trivially modified the grid (but maintain the same patch breakdown) - If I switch back to the smallest case, the code runs with no issues:

This breaks for both tfields and pfields, although the example here is pfields. 

All code / error output is here:

/gpfs/alpine/proj-shared/ast147/jmatteuc/flatfoil-summit-617342

**Comment by germasch** [comment]
Can you point me to where he job script is for this run, too? One possibility is that the code just ran out of (GPU) memory. If I can find the executable you ran, together with the core file, I may be able to figure out some more clues.

**Comment by jackmatt16** [comment]
Hi Kai, both the run script and the executable should now in that directory - although I will say I've tried the same job with 3x the GPUs to similar issues.  I'm trying 24 (6x) GPUs now.

**Comment by germasch** [comment]
These seems like a much more benign bug, which is related to colliions on the GPU. @jackmatt16 , can you check whether the fix (#66) that  merged into `master` resolves it for your case?

**Comment by germasch** [comment]
This particular issue is presumably fixed, though please reopen if trouble continues...
