### ISSUE TITLE
Code breaks at n_target = 2.5 and vacuum background

### ISSUE THREAD

**Issue by jackmatt16** [psc-code/psc#78]
Hi Kai,

I've found that the gpu code breaks at these higher target density cases (useful because n_target = 2.5 means n_ab = 1) and at vacuum background density. 

Error logs at:

/gpfs/alpine/proj-shared/ast147/jmatteuc/flatfoil-summit-742930

High target n_tar = 2.5 run file:
flatfoil_summit004.742907

Vacuum background, n_b = 0

flatfoil_summit004.742930

Thanks,
Jack

**Comment by germasch** [comment]
Sorry for not getting to this earlier. Could you share the psc_flatfoil_yz.cxx for the cases that break (I suppose you didn't modify any files other than that)?
